# -*- coding: utf-8 -*-
"""practice1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pA9AmJ_12k4wxMaclP09pW5L9AhlQCib
"""

#рабочая тетрадь 1.2
# 1
def bs(lst, k):
  lo = 0
  hi = len(lst) - 1
  if len(lst) == 0: #если список пустой, возвращаем 0
    return 0
  while lo <= hi:
    m = lo + (hi - lo) // 2 #находим середину текущего диапазона поиска
    mv = lst[m]
    if mv == k: #если середина совпала с искомым, возвращаем индекс
      return m
    if mv > k: #если середина больше искомого, сужаем поиск влево
      hi = m - 1
    else: #иначе искомое правее, сужаем поиск вправо
      lo = m + 1
  if len(lst) == 1: #особый случай: в списке ровно один элемент
    if k < lst[0]:
      return 0
    else:
      return 2

  if lst[0] < lst[-1]: #список отсортирован по возрастанию
    if k < lst[0]: #искомое меньше первого — позиция вставки в начале
      return 0
    elif k > lst[-1]: #искомое больше последнего — позиция вставки в конце
      return len(lst)
    else:
      for i in range(len(a)-1):
        if lst[i] < k < lst[i+1]:
          return i+1

  elif lst[0] > lst[-1]: #список отсортирован по убыванию
    if k > lst[0]:
      return 0
    elif k < lst[-1]:
      return len(lst)
    else:
      for i in range(len(a)-1):
        if lst[i] > k > lst[i+1]:
          return i+1

a = [8, 6, 5, 4, 3, 2, 1]
b = [1, 2, 4, 5, 6, 7, 8]
c = [1]
d = [1, 1, 1, 3, 4]
print(bs(a, 7))
print(bs(b, 3))
print(bs(c, 0))
print(bs(d, 2))

# 2
def ps(arr):
  if len(arr) < 3: #если элементов меньше трёх, массив не может быть горным
    print("Массив не горный")
  lo = 0
  hi = len(arr) - 1
  while lo < hi:
    m = lo + (hi - lo) // 2
    if arr[m] < arr[m+1]: #если подъём продолжается, пик находится правее
      lo = m + 1
    else: #иначе пик уже слева или совпадает с серединой
      hi = m

  if lo == 0 or lo == len(arr) - 1: #пик не может быть на краю массива
    return "Массив не горный"

  for i in range(lo): #проверяем, что до пика строгое возрастание
    if arr[i] >= arr[i+1]:
      return "Массив не горный"

  for i in range(lo, len(arr)-1): #проверяем, что после пика строгое убывание
    if arr[i] <= arr[i+1]:
      return "Массив не горный"

  return lo #возвращаем индекс найденного пика

a1 = [0, 2, 4, 3, 1]
print(ps(a1))

a2 = [0, 1, 2, 2, 1]
print(ps(a2)) #ожидаемый вывод: массив не горный

#задание 3
def neg(arr):
  cnt = 0 #счётчик отрицательных чисел
  lo = 0
  hi = len(arr) - 1
  while lo <= hi:
    m = lo + (hi - lo) // 2
    if arr[m] < 0: #если середина отрицательна, всё слева тоже отрицательно
      cnt = m + 1
      lo = m + 1
    else:
      hi = m - 1
  return cnt

def pos(arr):
  fst = -1 #индекс первого положительного элемента
  lo = 0
  hi = len(arr) - 1
  while lo <= hi:
    m = lo + (hi - lo) // 2
    if arr[m] > 0:
      hi = m - 1
      fst = m
    else:
      lo = m + 1
  if fst == -1:
    return 0
  return len(arr) - fst

a = [-5, -3, -1, 0, 0, 2, 4, 6, 8]
if a: #сравниваем количество отрицательных и положительных
  if neg(a) > pos(a):
    print("Отрицательных чисел больше:", neg(a))
  elif neg(a) < pos(a):
    print("Положительных чисел больше:", pos(a))
  else:
    print("Положительных и отрицательных чисел одинаковое количество:", pos(a))
else:
  print("Пустой массив")


# 4
def bs2(arr, x): #возвращает позицию для вставки x в отсортированный массив
  lo = 0
  hi = len(arr)
  while lo < hi:
    m = lo + (hi - lo) // 2
    if arr[m] < x: #все элементы до середины включительно меньше x, ищем правее
      lo = m + 1
    else: #позиция вставки находится в середине или левее
      hi = m
  return lo


def fl(arr):
  res = []
  seen = [] #список уже обработанных элементов
  for i in reversed(arr): #идём по массиву справа налево
    p = bs2(seen, i) #позиция вставки равна числу элементов, меньших i
    res.append(p)
    seen.insert(p, i)
    print(i, p, seen, res) #отладочный вывод
  return res[::-1]

a = [5, 2, 6, 1]
print(fl(a))