# -*- coding: utf-8 -*-
"""половинныйделитель.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEpvRu9GBDXGMZ4-c_HtjvQxGS5YHpGU
"""

#1
from math import *
l, r = map(int, input().split()) #ввод левой и правой границ
eps = float(input()) #ввод погрешности

def f(x): #задание функции
  return 3*x - 4*log10(x) - 5

while abs(r - l) > eps: #цикл нахождения корня
  b = l + (r - l) / 2
  if f(l) * f(b) < 0: #нахождение корня
    r = b
  else:
    l = b
  print(b)


#2
from math import *

def f(x): #задание функции
  return 3*x - 4*log10(x) - 5

def kor(l, r): #функция приближния корня
  return l - ((f(l)*(r-l))/(f(r)-f(l)))

l, r = map(int, input().split()) #ввод левой и правой границ
eps = float(input())      #ввод погрешности
cnt = 0

while r - l > eps:
  cnt += 1
  b = kor(l, r) #Вычисляем новое приближение
  if f(l) * f(b) > 0: #находим где лежит корень и уменьшаем интервал
    l = b
  else:
    r = b

  print(cnt, b)

print(b, f(b))