# -*- coding: utf-8 -*-
"""половинныйделитель.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEpvRu9GBDXGMZ4-c_HtjvQxGS5YHpGU
"""

from math import *
eps = 0.0001
l, r = map(int, input().split())

def f(x): #задание функции
  return 3*x - 4*log10(x) - 5

while abs(r - l) > eps: #цикл нахождения корня
  b = l + (r - l) / 2
  if f(l) * f(b) < 0: #нахождение корня
    r = b
  else:
    l = b
  print(b)